2023-03-27 12:10:37,314 (6433/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:10:37,314 (6433/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:10:37,324 (6433/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:10:37,324 (6433/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:10:37,331 (6433/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:10:37,331 (6433/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:10:37,341 (6433/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:10:37,341 (6433/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:11:30,028 (6433/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 520, in connect\n    _connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 479, in _connect\n    raise e\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 461, in _connect\n    self.sqlexecute = SQLExecute(\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 121, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 179, in connect\n    conn = pymysql.connect(\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 632, in connect\n    self._get_server_information()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1055, in _get_server_information\n    packet = self._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 692, in _read_packet\n    packet_header = self._read_bytes(4)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 748, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, \'Lost connection to MySQL server during query\')\n'
2023-03-27 12:12:59,564 (6584/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:12:59,564 (6584/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:12:59,574 (6584/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:12:59,574 (6584/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:12:59,580 (6584/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:12:59,581 (6584/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:12:59,595 (6584/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:12:59,596 (6584/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:13:51,677 (6584/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 520, in connect\n    _connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 479, in _connect\n    raise e\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 461, in _connect\n    self.sqlexecute = SQLExecute(\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 121, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 179, in connect\n    conn = pymysql.connect(\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 632, in connect\n    self._get_server_information()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1055, in _get_server_information\n    packet = self._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 692, in _read_packet\n    packet_header = self._read_bytes(4)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 748, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, \'Lost connection to MySQL server during query\')\n'
2023-03-27 12:14:31,313 (6643/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:14:31,314 (6643/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:14:31,323 (6643/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:14:31,323 (6643/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:14:31,330 (6643/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:14:31,330 (6643/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:14:31,339 (6643/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:14:31,340 (6643/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:15:23,829 (6643/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 520, in connect\n    _connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 479, in _connect\n    raise e\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 461, in _connect\n    self.sqlexecute = SQLExecute(\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 121, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 179, in connect\n    conn = pymysql.connect(\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 632, in connect\n    self._get_server_information()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1055, in _get_server_information\n    packet = self._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 692, in _read_packet\n    packet_header = self._read_bytes(4)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 748, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, \'Lost connection to MySQL server during query\')\n'
2023-03-27 12:15:49,300 (6866/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:15:49,301 (6866/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:15:49,310 (6866/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:15:49,310 (6866/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:15:49,317 (6866/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:15:49,317 (6866/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:15:49,326 (6866/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:15:49,327 (6866/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:15:49,353 (6866/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 520, in connect\n    _connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 479, in _connect\n    raise e\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 461, in _connect\n    self.sqlexecute = SQLExecute(\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 121, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 179, in connect\n    conn = pymysql.connect(\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect\n    self._request_authentication()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication\n    auth_packet = self._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1698, "Access denied for user \'root\'@\'localhost\'")\n'
2023-03-27 12:16:00,347 (6891/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:16:00,348 (6891/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:00,357 (6891/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:16:00,357 (6891/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:00,364 (6891/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:16:00,364 (6891/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:00,373 (6891/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:16:00,374 (6891/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:03,565 (6891/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 461, in _connect\n    self.sqlexecute = SQLExecute(\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 121, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 179, in connect\n    conn = pymysql.connect(\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect\n    self._request_authentication()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication\n    auth_packet = self._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1045, "Access denied for user \'eric\'@\'localhost\' (using password: NO)")\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 520, in connect\n    _connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 473, in _connect\n    self.sqlexecute = SQLExecute(\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 121, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 179, in connect\n    conn = pymysql.connect(\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__\n    self.connect()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect\n    self._request_authentication()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication\n    auth_packet = self._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1049, "Unknown database \'test_db\'")\n'
2023-03-27 12:16:32,622 (6958/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:16:32,622 (6958/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:32,632 (6958/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:16:32,632 (6958/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:32,639 (6958/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:16:32,639 (6958/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:32,648 (6958/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:16:32,648 (6958/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:35,130 (6958/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:16:35,130 (6958/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:16:35,139 (6958/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:16:35,139 (6958/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:22:51,097 (7321/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:22:51,097 (7321/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:22:51,107 (7321/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:22:51,107 (7321/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:23:59,715 (7356/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:23:59,715 (7356/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:23:59,725 (7356/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:23:59,725 (7356/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:04,515 (7360/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:24:04,516 (7360/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:04,525 (7360/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:24:04,526 (7360/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:11,008 (7376/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:24:11,008 (7376/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:11,018 (7376/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:24:11,018 (7376/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:11,024 (7376/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:24:11,025 (7376/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:11,039 (7376/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:24:11,040 (7376/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:11,063 (7376/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:24:11,063 (7376/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:11,073 (7376/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:24:11,074 (7376/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:58,793 (7400/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:24:58,794 (7400/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:58,804 (7400/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:24:58,804 (7400/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:58,810 (7400/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:24:58,810 (7400/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:58,825 (7400/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:24:58,825 (7400/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:58,848 (7400/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:24:58,848 (7400/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:24:58,858 (7400/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:24:58,858 (7400/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:38:13,975 (8082/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:38:13,975 (8082/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:38:13,985 (8082/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:38:13,985 (8082/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:38:13,991 (8082/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:38:13,992 (8082/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:38:14,006 (8082/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:38:14,007 (8082/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:38:14,029 (8082/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 12:38:14,029 (8082/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:38:14,039 (8082/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 12:38:14,040 (8082/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 12:38:24,746 (8082/MainThread) mycli.main ERROR - sql: '/dt;', error: ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/dt' at line 1")
2023-03-27 12:38:24,757 (8082/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'/dt\' at line 1")\n'
2023-03-27 12:39:27,505 (8082/MainThread) mycli.main ERROR - sql: '\\dt+ movies', error: OperationalError(1046, 'No database selected')
2023-03-27 12:39:27,507 (8082/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 75, in execute\n    return special_cmd.handler(cur=cur, arg=arg, verbose=verbose)\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/dbcommands.py", line 21, in list_tables\n    cur.execute(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1046, \'No database selected\')\n'
2023-03-27 12:47:15,505 (8082/MainThread) mycli.main ERROR - sql: '\\dt+ games;', error: ProgrammingError(1146, "Table 'games.games' doesn't exist")
2023-03-27 12:47:15,507 (8082/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 75, in execute\n    return special_cmd.handler(cur=cur, arg=arg, verbose=verbose)\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/dbcommands.py", line 21, in list_tables\n    cur.execute(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.ProgrammingError: (1146, "Table \'games.games\' doesn\'t exist")\n'
2023-03-27 13:51:13,422 (9584/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:51:13,422 (9584/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:13,432 (9584/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:51:13,432 (9584/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:45,884 (9676/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:51:45,884 (9676/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:45,894 (9676/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:51:45,894 (9676/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:54,127 (9699/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:51:54,128 (9699/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:54,138 (9699/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:51:54,138 (9699/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:54,144 (9699/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:51:54,145 (9699/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:54,159 (9699/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:51:54,160 (9699/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:54,183 (9699/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:51:54,183 (9699/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:51:54,194 (9699/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:51:54,194 (9699/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:53:41,503 (9699/MainThread) mycli.main ERROR - sql: 'CREATE INDEX idx_houses_lat_long ON houses (latitude, longitude);', error: OperationalError(1142, "INDEX command denied to user 'eric'@'localhost' for table `real_estate`.`houses`")
2023-03-27 13:53:41,514 (9699/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1142, "INDEX command denied to user \'eric\'@\'localhost\' for table `real_estate`.`houses`")\n'
2023-03-27 13:57:18,983 (9699/MainThread) mycli.main ERROR - sql: 'create index idx_houses_lat_long on houses;', error: ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1")
2023-03-27 13:57:18,984 (9699/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'\' at line 1")\n'
2023-03-27 13:57:36,173 (9699/MainThread) mycli.main ERROR - sql: 'create index idx_houses_lat_long on houses (latitude, longitude);', error: OperationalError(1142, "INDEX command denied to user 'eric'@'localhost' for table `real_estate`.`houses`")
2023-03-27 13:57:36,176 (9699/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1142, "INDEX command denied to user \'eric\'@\'localhost\' for table `real_estate`.`houses`")\n'
2023-03-27 13:58:41,049 (9886/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:58:41,049 (9886/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:58:41,059 (9886/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:58:41,059 (9886/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:58:49,522 (9907/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:58:49,523 (9907/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:58:49,533 (9907/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:58:49,533 (9907/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:58:49,539 (9907/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:58:49,539 (9907/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:58:49,554 (9907/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:58:49,555 (9907/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:58:49,577 (9907/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 13:58:49,577 (9907/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:58:49,588 (9907/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 13:58:49,589 (9907/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 13:59:56,257 (9907/MainThread) mycli.main ERROR - sql: "grant all privileges on real_estate to 'eric'@'localhost';", error: OperationalError(1046, 'No database selected')
2023-03-27 13:59:56,268 (9907/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1046, \'No database selected\')\n'
2023-03-27 14:00:17,669 (9957/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:00:17,670 (9957/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:00:17,680 (9957/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:00:17,680 (9957/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:00:17,686 (9957/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:00:17,687 (9957/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:00:17,701 (9957/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:00:17,702 (9957/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:00:17,724 (9957/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:00:17,725 (9957/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:00:17,735 (9957/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:00:17,735 (9957/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:00:32,544 (9957/MainThread) mycli.main ERROR - sql: 'create index idx_houses_lat_long on houses (latitude, longitude);', error: OperationalError(1142, "INDEX command denied to user 'eric'@'localhost' for table `real_estate`.`houses`")
2023-03-27 14:00:32,550 (9957/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1142, "INDEX command denied to user \'eric\'@\'localhost\' for table `real_estate`.`houses`")\n'
2023-03-27 14:05:43,433 (10072/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:05:43,433 (10072/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:05:43,443 (10072/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:05:43,443 (10072/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:05:43,449 (10072/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:05:43,450 (10072/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:05:43,464 (10072/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:05:43,465 (10072/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:05:43,487 (10072/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:05:43,488 (10072/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:05:43,498 (10072/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:05:43,498 (10072/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:06:56,968 (10072/MainThread) mycli.main ERROR - sql: "grant all privileges on real_estate to 'eric'@'localhost';", error: OperationalError(1046, 'No database selected')
2023-03-27 14:06:56,975 (10072/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1046, \'No database selected\')\n'
2023-03-27 14:11:01,910 (10261/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:11:01,911 (10261/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:01,921 (10261/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:11:01,921 (10261/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:01,927 (10261/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:11:01,927 (10261/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:01,942 (10261/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:11:01,943 (10261/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:01,965 (10261/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:11:01,966 (10261/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:01,976 (10261/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:11:01,976 (10261/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:55,548 (10338/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:11:55,549 (10338/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:55,558 (10338/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:11:55,559 (10338/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:55,565 (10338/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:11:55,565 (10338/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:55,580 (10338/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:11:55,580 (10338/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:55,603 (10338/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:11:55,603 (10338/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:11:55,613 (10338/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:11:55,614 (10338/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:28,857 (10396/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:13:28,858 (10396/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:28,868 (10396/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:13:28,868 (10396/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:28,874 (10396/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:13:28,874 (10396/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:28,889 (10396/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:13:28,890 (10396/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:28,912 (10396/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:13:28,912 (10396/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:28,922 (10396/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:13:28,923 (10396/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:45,789 (10417/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:13:45,790 (10417/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:45,800 (10417/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:13:45,800 (10417/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:45,806 (10417/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:13:45,807 (10417/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:45,822 (10417/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:13:45,822 (10417/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:45,844 (10417/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-27 14:13:45,845 (10417/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:45,855 (10417/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-27 14:13:45,855 (10417/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-27 14:13:54,404 (10417/MainThread) mycli.main ERROR - sql: 'create index idx_houses_lat_long on houses (latitude, longitude);', error: OperationalError(1046, 'No database selected')
2023-03-27 14:13:54,410 (10417/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1046, \'No database selected\')\n'
2023-03-27 14:28:30,070 (10417/MainThread) mycli.main ERROR - sql: 'SELECT *, SQRT(POW(69.1 * (latitude - <given_latitude>), 2) + POW(69.1 * (<given_longitude> - longitude) * COS(latitude / 57.3), 2)) AS distance\nFROM houses\nHAVING distance < <given_distance_in_miles>\nORDER BY distance;', error: ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '<given_latitude>), 2) + POW(69.1 * (<given_longitude> - longitude) * COS(lati...' at line 1")
2023-03-27 14:28:30,072 (10417/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'<given_latitude>), 2) + POW(69.1 * (<given_longitude> - longitude) * COS(lati...\' at line 1")\n'
2023-03-29 11:09:53,918 (44251/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 11:09:53,920 (44251/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:09:53,931 (44251/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 11:09:53,931 (44251/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:09:53,936 (44251/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 11:09:53,937 (44251/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:09:53,950 (44251/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 11:09:53,950 (44251/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:09:53,984 (44251/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 11:09:53,984 (44251/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:09:53,993 (44251/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 11:09:53,993 (44251/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:38:46,470 (44772/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 11:38:46,471 (44772/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:38:46,478 (44772/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 11:38:46,479 (44772/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:38:46,484 (44772/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 11:38:46,484 (44772/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:38:46,497 (44772/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 11:38:46,497 (44772/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:38:46,517 (44772/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 11:38:46,518 (44772/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:38:46,526 (44772/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 11:38:46,526 (44772/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 11:38:59,908 (44772/MainThread) mycli.main ERROR - sql: 'CREATE TABLE `programming_languages`\n(\n  `id`            INT(11) NOT NULL auto_increment ,\n  `name`          VARCHAR(255) NOT NULL ,\n  `released_year` INT NOT NULL ,\n  `githut_rank`   INT NULL ,\n  `pypl_rank`     INT NULL ,\n  `tiobe_rank`    INT NULL ,\n  `created_at`    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,\n  `updated_at`    DATETIME on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,\n  PRIMARY KEY (`id`),\n  UNIQUE `idx_name_unique` (`name`(255))\n)\nengine = innodb charset=utf8mb4 COLLATE utf8mb4_general_ci;', error: OperationalError(1046, 'No database selected')
2023-03-29 11:38:59,924 (44772/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1046, \'No database selected\')\n'
2023-03-29 16:43:40,529 (50192/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 16:43:40,529 (50192/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 16:43:40,539 (50192/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 16:43:40,539 (50192/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 16:43:40,544 (50192/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 16:43:40,545 (50192/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 16:43:40,558 (50192/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 16:43:40,558 (50192/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 16:43:40,578 (50192/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 16:43:40,579 (50192/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 16:43:40,587 (50192/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 16:43:40,587 (50192/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 17:10:45,031 (50923/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 17:10:45,032 (50923/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 17:10:45,040 (50923/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 17:10:45,040 (50923/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 17:10:45,045 (50923/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 17:10:45,046 (50923/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 17:10:45,059 (50923/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 17:10:45,059 (50923/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 17:10:45,079 (50923/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-29 17:10:45,080 (50923/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-29 17:10:45,089 (50923/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-29 17:10:45,089 (50923/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-30 12:07:00,937 (5930/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-30 12:07:00,941 (5930/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-30 12:07:00,951 (5930/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-30 12:07:00,952 (5930/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-30 12:07:00,959 (5930/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-30 12:07:00,959 (5930/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-30 12:07:00,977 (5930/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-30 12:07:00,978 (5930/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-30 12:07:01,001 (5930/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-03-30 12:07:01,002 (5930/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-03-30 12:07:01,012 (5930/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-03-30 12:07:01,012 (5930/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-04 15:39:28,223 (7533/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-04 15:39:28,225 (7533/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-04 15:39:28,233 (7533/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-04 15:39:28,234 (7533/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-04 15:39:28,239 (7533/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-04 15:39:28,239 (7533/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-04 15:39:28,252 (7533/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-04 15:39:28,252 (7533/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-04 15:39:28,272 (7533/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-04 15:39:28,273 (7533/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-04 15:39:28,281 (7533/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-04 15:39:28,281 (7533/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-04 15:39:33,786 (7533/MainThread) mycli.main ERROR - sql: '\\dt', error: OperationalError(1046, 'No database selected')
2023-04-04 15:39:33,808 (7533/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 75, in execute\n    return special_cmd.handler(cur=cur, arg=arg, verbose=verbose)\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/dbcommands.py", line 21, in list_tables\n    cur.execute(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1046, \'No database selected\')\n'
2023-04-24 11:29:45,954 (5952/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-24 11:29:45,956 (5952/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-24 11:29:45,967 (5952/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-24 11:29:45,967 (5952/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-24 11:29:45,973 (5952/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-24 11:29:45,974 (5952/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-24 11:29:45,988 (5952/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-24 11:29:45,989 (5952/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-24 11:29:46,035 (5952/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-24 11:29:46,036 (5952/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-24 11:29:46,046 (5952/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-24 11:29:46,046 (5952/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 12:58:43,577 (10857/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-28 12:58:43,579 (10857/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 12:58:43,601 (10857/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-28 12:58:43,601 (10857/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 12:58:43,608 (10857/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-28 12:58:43,608 (10857/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 12:58:43,623 (10857/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-28 12:58:43,623 (10857/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 12:58:43,656 (10857/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-28 12:58:43,657 (10857/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 12:58:43,667 (10857/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-28 12:58:43,668 (10857/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 12:58:50,285 (10857/MainThread) mycli.main ERROR - sql: '\\dt', error: OperationalError(1046, 'No database selected')
2023-04-28 12:58:50,307 (10857/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/main.py", line 75, in execute\n    return special_cmd.handler(cur=cur, arg=arg, verbose=verbose)\n  File "/home/eric/.local/lib/python3.10/site-packages/mycli/packages/special/dbcommands.py", line 21, in list_tables\n    cur.execute(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute\n    result = self._query(query)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1046, \'No database selected\')\n'
2023-04-28 16:36:16,004 (18343/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-28 16:36:16,004 (18343/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 16:36:16,016 (18343/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-28 16:36:16,016 (18343/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 16:36:16,023 (18343/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-28 16:36:16,023 (18343/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 16:36:16,038 (18343/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-28 16:36:16,038 (18343/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 16:36:16,061 (18343/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-04-28 16:36:16,061 (18343/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-04-28 16:36:16,071 (18343/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-04-28 16:36:16,072 (18343/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:22,357 (6734/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-19 09:40:22,359 (6734/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:22,367 (6734/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-19 09:40:22,368 (6734/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:22,373 (6734/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-19 09:40:22,373 (6734/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:22,382 (6734/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-19 09:40:22,382 (6734/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:25,994 (6734/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/main.py", line 487, in connect\n    _connect()\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/main.py", line 471, in _connect\n    new_passwd = click.prompt(\'Password\', hide_input=True,\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/click/termui.py", line 166, in prompt\n    value = prompt_func(prompt)\n            ^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/click/termui.py", line 149, in prompt_func\n    raise Abort() from None\nclick.exceptions.Abort\n'
2023-05-19 09:40:32,341 (6748/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-19 09:40:32,341 (6748/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:32,350 (6748/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-19 09:40:32,351 (6748/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:32,356 (6748/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-19 09:40:32,356 (6748/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:32,364 (6748/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-19 09:40:32,365 (6748/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:32,411 (6748/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-19 09:40:32,412 (6748/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:32,420 (6748/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-19 09:40:32,421 (6748/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:40:37,964 (6748/MainThread) mycli.main ERROR - sql: '\\dt', error: OperationalError(1046, 'No database selected')
2023-05-19 09:40:37,975 (6748/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/packages/special/main.py", line 75, in execute\n    return special_cmd.handler(cur=cur, arg=arg, verbose=verbose)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/packages/special/dbcommands.py", line 21, in list_tables\n    cur.execute(query)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/cursors.py", line 158, in execute\n    result = self._query(query)\n             ^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/cursors.py", line 325, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 549, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 779, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 1157, in read\n    first_packet = self.connection._read_packet()\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 729, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1046, \'No database selected\')\n'
2023-05-19 09:41:01,712 (6777/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-19 09:41:01,712 (6777/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:41:01,721 (6777/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-19 09:41:01,721 (6777/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:41:01,726 (6777/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-19 09:41:01,727 (6777/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:41:01,735 (6777/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-19 09:41:01,735 (6777/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:41:01,781 (6777/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-19 09:41:01,781 (6777/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-19 09:41:01,790 (6777/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-19 09:41:01,790 (6777/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:09:36,241 (6984/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-24 16:09:36,242 (6984/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:09:36,251 (6984/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-24 16:09:36,252 (6984/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:09:36,257 (6984/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-24 16:09:36,257 (6984/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:09:36,265 (6984/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-24 16:09:36,266 (6984/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:09:36,334 (6984/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-24 16:09:36,334 (6984/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:09:36,342 (6984/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-24 16:09:36,343 (6984/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:11:43,345 (7052/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-24 16:11:43,346 (7052/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:11:43,354 (7052/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-24 16:11:43,355 (7052/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:11:43,360 (7052/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-24 16:11:43,360 (7052/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:11:43,368 (7052/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-24 16:11:43,369 (7052/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:11:43,415 (7052/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-24 16:11:43,415 (7052/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-24 16:11:43,424 (7052/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-24 16:11:43,424 (7052/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-29 16:45:01,286 (2696/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-29 16:45:01,287 (2696/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-29 16:45:01,296 (2696/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-29 16:45:01,297 (2696/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-29 16:45:01,302 (2696/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-29 16:45:01,303 (2696/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-29 16:45:01,311 (2696/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-29 16:45:01,311 (2696/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-29 16:45:01,358 (2696/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-29 16:45:01,359 (2696/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-29 16:45:01,367 (2696/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-29 16:45:01,367 (2696/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 11:41:21,934 (3366/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 11:41:21,935 (3366/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 11:41:21,943 (3366/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 11:41:21,943 (3366/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 11:41:21,947 (3366/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 11:41:21,948 (3366/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 11:41:21,954 (3366/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 11:41:21,954 (3366/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 11:41:22,013 (3366/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 11:41:22,013 (3366/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 11:41:22,020 (3366/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 11:41:22,020 (3366/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 11:41:34,443 (3366/MainThread) mycli.main ERROR - sql: '/dt;', error: ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/dt' at line 1")
2023-05-31 11:41:34,469 (3366/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/cursors.py", line 158, in execute\n    result = self._query(query)\n             ^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/cursors.py", line 325, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 549, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 779, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 1157, in read\n    first_packet = self.connection._read_packet()\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 729, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'/dt\' at line 1")\n'
2023-05-31 11:41:39,435 (3366/MainThread) mycli.main ERROR - sql: '/dt;', error: ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/dt' at line 1")
2023-05-31 11:41:39,440 (3366/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/cursors.py", line 158, in execute\n    result = self._query(query)\n             ^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/cursors.py", line 325, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 549, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 779, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 1157, in read\n    first_packet = self.connection._read_packet()\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 729, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'/dt\' at line 1")\n'
2023-05-31 11:41:43,938 (3366/MainThread) mycli.main ERROR - sql: 'ls\n;', error: ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ls' at line 1")
2023-05-31 11:41:43,944 (3366/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/sqlexecute.py", line 248, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/packages/special/main.py", line 58, in execute\n    raise CommandNotFound\nmycli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/main.py", line 726, in one_iteration\n    for title, cur, headers, status in res:\n  File "/home/eric/.local/lib/python3.11/site-packages/mycli/sqlexecute.py", line 252, in run\n    cur.execute(sql)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/cursors.py", line 158, in execute\n    result = self._query(query)\n             ^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/cursors.py", line 325, in _query\n    conn.query(q)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 549, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 779, in _read_query_result\n    result.read()\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 1157, in read\n    first_packet = self.connection._read_packet()\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/connections.py", line 729, in _read_packet\n    packet.raise_for_error()\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/home/eric/.local/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'ls\' at line 1")\n'
2023-05-31 17:38:27,273 (14540/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 17:38:27,275 (14540/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:38:27,284 (14540/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 17:38:27,284 (14540/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:38:27,289 (14540/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 17:38:27,290 (14540/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:38:27,298 (14540/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 17:38:27,298 (14540/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:38:27,366 (14540/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 17:38:27,367 (14540/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:38:27,375 (14540/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 17:38:27,376 (14540/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:39:25,237 (14597/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 17:39:25,237 (14597/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:39:25,246 (14597/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 17:39:25,246 (14597/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:39:25,252 (14597/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 17:39:25,252 (14597/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:39:25,260 (14597/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 17:39:25,261 (14597/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:39:25,308 (14597/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-05-31 17:39:25,308 (14597/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-05-31 17:39:25,316 (14597/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-05-31 17:39:25,317 (14597/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 13:52:35,235 (16553/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 13:52:35,237 (16553/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 13:52:35,246 (16553/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 13:52:35,246 (16553/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 13:52:35,252 (16553/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 13:52:35,252 (16553/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 13:52:35,261 (16553/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 13:52:35,261 (16553/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 13:52:35,311 (16553/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 13:52:35,311 (16553/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 13:52:35,320 (16553/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 13:52:35,320 (16553/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:06:05,433 (3478/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 17:06:05,434 (3478/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:06:05,444 (3478/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 17:06:05,444 (3478/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:06:05,450 (3478/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 17:06:05,450 (3478/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:06:05,458 (3478/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 17:06:05,459 (3478/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:06:05,511 (3478/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 17:06:05,511 (3478/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:06:05,521 (3478/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 17:06:05,522 (3478/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:26:08,455 (5162/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 17:26:08,455 (5162/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:26:08,464 (5162/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 17:26:08,465 (5162/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:26:08,470 (5162/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 17:26:08,470 (5162/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:26:08,479 (5162/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 17:26:08,480 (5162/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:26:08,529 (5162/MainThread) mycli.config WARNING - Unable to parse line 10 of config file '/etc/my.cnf'.
2023-06-01 17:26:08,529 (5162/MainThread) mycli.config WARNING - Using successfully parsed config values.
2023-06-01 17:26:08,539 (5162/MainThread) mycli.config WARNING - Unable to parse line 1 of config file '/home/eric/.my.cnf'.
2023-06-01 17:26:08,539 (5162/MainThread) mycli.config WARNING - Using successfully parsed config values.
